[start]
cmd = "php -S 0.0.0.0:${PORT:-3000} -t ."

[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = [
    "rm -rf vendor",
    "composer install --no-dev --optimize-autoloader",
    "composer dump-autoload --optimize"
]

[phases.build]
cmds = [
    "mkdir -p /tmp/miw_uploads/documents",
    "mkdir -p /tmp/miw_uploads/payments", 
    "mkdir -p /tmp/miw_uploads/photos",
    "mkdir -p /tmp/miw_uploads/cancellations",
    "chmod -R 777 /tmp/miw_uploads"
]

[variables]
PORT = "3000"
